project:
  type: website

website:
  title: "Henry Towbin"
  output-dir: docs
  navbar:
    right:
      - about.qmd
      - posts_listing_page.qmd
      - icon: github
        href: https://github.com/whtowbin
      - icon: linkedin
        href: https://www.linkedin.com/in/henry-towbin-22104765
  page-footer: 
    left:
      - text: "Henry Towbin 2024"
    right:
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/henry-towbin-22104765
      - icon: github
        text: Github
        href: https://github.com/whtowbin

format:
  html:
    theme: cosmo
    css: styles.css

resources:
  - CNAME

execute:
  freeze: auto


